version: '3.3'

services:
  data_api:
    # build: .
    build:
      context: .
      dockerfile: ./data_api/Dockerfile.development
    restart: always
    ports:
      - '3030:3030'
    expose:
      - 3030
    environment:
      - HOST=0.0.0.0
      - PORT=3030
    volumes:
      - ./data_api:/home/node/app
    networks:
      - proximus_website_network

  postgres_db_server:
    image: postgres:12.5
    command: ['postgres', '-c', 'log_statement=all']
    restart: always
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - proximus_website_data_api_postgres_db_01:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - proximus_website_network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - proximus_website_network

networks:
  proximus_website_network:
    driver: bridge

volumes:
  # loopback-postgres-db3:
  proximus_website_data_api_postgres_db_01:
