# Check out https://hub.docker.com/_/node to select a new base image
FROM node:14

RUN npm install pm2 -g

# Set to a non-root built-in user `node`
USER node

# Create app directory (with user `node`)
RUN mkdir -p /home/node/app

WORKDIR /home/node/app

# Bind to all network interfaces so that it can be mapped to the host OS
# ENV HOST=0.0.0.0 PORT=3000

ENV TZ=Europe/London

# EXPOSE ${PORT}
CMD [ "./run-development.sh" ]
